from __future__ import annotations

from pathlib import Path

from curated_knowledge_markdown import build_chunks, entry_slug

PAGE_SIZE = 140


def write_document_bundle(
    raw_path: Path,
    raw_root: Path,
    curated_root: Path,
    metadata: dict[str, object],
) -> dict[str, object]:
    relative_path = raw_path.relative_to(raw_root).as_posix()
    document_dir = curated_root / "entries" / entry_slug(relative_path)
    document_dir.mkdir(parents=True, exist_ok=True)
    chunks = build_chunks(relative_path, raw_path.read_text(encoding="utf-8"), raw_path.suffix.lower())
    chunk_records = _write_chunks(document_dir, metadata, relative_path, chunks)
    index_pages = _write_chunk_index_pages(document_dir, relative_path, chunk_records)
    (document_dir / "README.md").write_text(
        _document_readme(metadata, relative_path, curated_root, document_dir, chunk_records, index_pages),
        encoding="utf-8",
    )
    return {
        "raw_path": relative_path,
        "entry_dir": document_dir.relative_to(curated_root).as_posix(),
        "chunk_count": len(chunk_records),
        "generated_files": len(chunk_records) + len(index_pages) + 1,
    }


def write_catalog_pages(
    curated_root: Path,
    source_name: str,
    records: list[dict[str, object]],
) -> list[str]:
    catalog_dir = curated_root / "catalog"
    catalog_dir.mkdir(parents=True, exist_ok=True)
    page_paths = []
    for page_number, start in enumerate(range(0, len(records), PAGE_SIZE), start=1):
        page_name = f"page-{page_number:03}.md"
        lines = [
            f"# {source_name} catalog page {page_number}",
            "",
            "Browse document bundles without rescanning raw docs.",
            "",
        ]
        for record in records[start : start + PAGE_SIZE]:
            lines.append(
                f"- `{record['raw_path']}` -> `{record['entry_dir']}/README.md` ({record['chunk_count']} chunks)"
            )
        (catalog_dir / page_name).write_text("\n".join(lines) + "\n", encoding="utf-8")
        page_paths.append(f"catalog/{page_name}")
    return page_paths


def write_source_readme(
    curated_root: Path,
    metadata: dict[str, object],
    records: list[dict[str, object]],
    page_paths: list[str],
) -> None:
    chunk_total = sum(int(record["chunk_count"]) for record in records)
    lines = [
        f"# Curated {metadata['name']} knowledge",
        "",
        "Generated by `python scripts/bootstrap_curated_knowledge.py` from synced raw docs.",
        "",
        f"- repo: `{metadata['repo_url']}`",
        f"- commit: `{metadata['commit']}`",
        f"- raw tree: `{metadata['raw_output']}`",
        f"- raw documents: {len(records)}",
        f"- curated chunks: {chunk_total}",
        "",
        "## Browse",
        "",
        "- `entries/` mirrors the synced raw paths as reviewable chunk bundles.",
        "- `catalog/` provides paginated indexes for quick topic discovery.",
        "",
        "## Top-level groups",
        "",
    ]
    lines.extend(f"- `{group}`: {count} docs" for group, count in _group_counts(records))
    lines.extend(["", "## Catalog pages", ""])
    lines.extend(f"- `{page}`" for page in page_paths)
    (curated_root / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_chunks(
    document_dir: Path,
    metadata: dict[str, object],
    relative_path: str,
    chunks: list[dict[str, object]],
) -> list[dict[str, object]]:
    records = []
    for position, chunk in enumerate(chunks, start=1):
        file_name = f"chunk-{position:03}.md"
        (document_dir / file_name).write_text(
            _chunk_markdown(metadata, relative_path, position, len(chunks), chunk),
            encoding="utf-8",
        )
        records.append(
            {
                "file_name": file_name,
                "heading_path_text": chunk["heading_path_text"],
                "line_start": chunk["line_start"],
                "line_end": chunk["line_end"],
            }
        )
    return records


def _write_chunk_index_pages(
    document_dir: Path,
    relative_path: str,
    chunk_records: list[dict[str, object]],
) -> list[str]:
    page_names = []
    for page_number, start in enumerate(range(0, len(chunk_records), PAGE_SIZE), start=1):
        page_name = f"index-{page_number:03}.md"
        lines = [f"# `{relative_path}` chunk index page {page_number}", ""]
        for chunk in chunk_records[start : start + PAGE_SIZE]:
            lines.append(
                f"- `{chunk['file_name']}` - `{chunk['heading_path_text']}` - lines `{chunk['line_start']}-{chunk['line_end']}`"
            )
        (document_dir / page_name).write_text("\n".join(lines) + "\n", encoding="utf-8")
        page_names.append(page_name)
    return page_names


def _document_readme(
    metadata: dict[str, object],
    relative_path: str,
    curated_root: Path,
    document_dir: Path,
    chunk_records: list[dict[str, object]],
    index_pages: list[str],
) -> str:
    lines = [
        f"# `{relative_path}`",
        "",
        f"- source: `{metadata['name']}`",
        f"- repo: `{metadata['repo_url']}`",
        f"- commit: `{metadata['commit']}`",
        f"- raw path: `{relative_path}`",
        f"- bundle: `{document_dir.relative_to(curated_root).as_posix()}`",
        f"- chunks: {len(chunk_records)}",
        "",
        "## Chunk index pages",
        "",
    ]
    lines.extend(f"- `{page_name}`" for page_name in index_pages)
    return "\n".join(lines) + "\n"


def _chunk_markdown(
    metadata: dict[str, object],
    relative_path: str,
    position: int,
    total: int,
    chunk: dict[str, object],
) -> str:
    lines = [
        f"# `{relative_path}` chunk {position:03}",
        "",
        f"- source: `{metadata['name']}`",
        f"- repo: `{metadata['repo_url']}`",
        f"- commit: `{metadata['commit']}`",
        f"- raw path: `{relative_path}`",
        f"- heading path: `{chunk['heading_path_text']}`",
        f"- lines: `{chunk['line_start']}-{chunk['line_end']}`",
        f"- chunk: `{position} of {total}`",
        "",
        "## Extract",
        "",
        "``````text",
        *chunk["lines"],
        "``````",
    ]
    return "\n".join(lines) + "\n"


def _group_counts(records: list[dict[str, object]]) -> list[tuple[str, int]]:
    counts: dict[str, int] = {}
    for record in records:
        group = str(record["raw_path"]).split("/", 1)[0]
        counts[group] = counts.get(group, 0) + 1
    return sorted(counts.items())
